services:

  postgres:
    image: postgres:latest
    container_name: ${APP_VER_NAME}-${POSTGRES_CONTAINER_NAME}
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  airflow-init:
    image: apache/airflow:2.7.3
    container_name: airflow-init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    command: >
      bash -c "airflow db init &&
      airflow users create
      --username admin
      --password admin
      --firstname admin
      --lastname admin
      --role Admin
      --email admin@example.com"

  airflow-webserver:
    image: apache/airflow:2.7.3
    container_name: airflow-webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    ports:
      - ${AIRFLOW_PORT}:${AIRFLOW_PORT}
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.3
    container_name: airflow-scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    command: scheduler

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"

      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  spark-master:
    image: apache/spark:3.5.1-python3
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - ${SPARK_1_PORT}:${SPARK_1_PORT}
      - ${SPARK_2_PORT}:${SPARK_2_PORT}
    volumes:
      - ./spark_jobs:/opt/spark/jobs

  spark-worker:
    image: apache/spark:3.5.1-python3
    container_name: spark-worker
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - ./spark_jobs:/opt/spark/jobs

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb_data:/data/db

  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: prometheus
    ports:
      - ${PROMOTHEUS_PORT}:${PROMOTHEUS_PORT}
    volumes:
      - ./monitoring:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  mongodb_data:
  grafana_data: